### ISSUE TITLE
File not found

### ISSUE THREAD

**Issue by prpanto** [directus-labs/directus-template-cli#70] opened 2024-12-22 14:39 UTC
directus version: 11.3.5

```
$ npx directus-template-cli apply
=== Directus Template CLI - Apply

? What type of template would you like to apply? Community templates
? Select a template. Headless CMS - Website
You selected Headless CMS - Website
------------------
What is your Directus URL? [http://localhost:8055]: 
? How do you want to log in? Directus Access Token
What is your Directus Admin Token?: 
-- Logged in as Admin User
=== Applying template - Headless CMS - Website to http://localhost:8055

Loading 39 collections and 300 fields... done
Loading 64 relations... done
Loading 3 roles... done
 ›   Warning: Unknown error: "File not found: 
 ›   /.../node_modules/directus-template-cli/dist/lib/downloads/official/website-cms/src/policies.json"
    Error: ENOENT: no such file or directory, open 
    '/.../node_modules/directus-template-cli/dist/lib/downloads/official/website-cms/src/policies.json'
    Code: ENOENT
```

**Comment by bryantgillespie** [comment] 2024-12-27 13:48
Duplicate of #68

**Closed by bryantgillespie** 2024-12-27 13:48 UTC
